# <center>Aston University <br/><br/> CS3IVP: Digital Image and Video Processing <br/><br/> Lab 01: Working with matrices and vectorising code</center>

Academic year: 2024-2025 <br/>
Lecturer: Dr. Debaleena Roy<a href="mailto:d.roy@aston.ac.uk">d.roy@aston.ac.uk</a> <br/>
Office: MB265K <br/>

## Goals
By the end of this session, you should know:
1. how to create, access and update NumPy matrices and vectors,
2. how to perform element-wise operations,
3. how to work with array slices
4. how to work with boolean masks
5. how to vectorise loop-based matrix manipulation code.

You can get extra help by looking at the official documentation of the software we'll use:
- [Jupyter - https://jupyter.org/documentation](https://jupyter.org/documentation)
- [Python 3 - https://docs.python.org/3/tutorial/](https://docs.python.org/3/tutorial/)
- [NumPy - https://numpy.org/doc/](https://numpy.org/doc/)


## Instructions
No submission is required for this laboratory.

## Recap and minor comments
In `Lab 00` we learned how to create and operate matrices:

In [2]:
import numpy

matrix1 = numpy.array([
    [1,2],
    [3,4],
    [5,6]])

matrix2 = numpy.array([
    [10,20],
    [10,20],
    [10,20]])

We can add and multiply matrices of the same shape using the regular operators, as NumPy works element-wise by default (i.e., `*` is not interpreted as matrix multiplication but as element-wise matrix multiplication). For "real" matrix multiplication we need to use the `@` operator. We will see more on that later.

In [3]:
print( matrix1 + matrix2 )

print( matrix1 * matrix2 )

[[11 22]
 [13 24]
 [15 26]]
[[ 10  40]
 [ 30  80]
 [ 50 120]]


We also covered the most useful NumPy array attributes:
- `ndim` is the number of dimensions of the array.
- `shape` is a tuple containing the length of the array in each dimension.
- `size` is the number of items in the array.
- `dtype` is the type of the items the array holds. A lot of NumPy functions accept `dtype` as a parameter as well.

See the corresponding values for our previous example:

In [4]:
print(f'addition.ndim is:   {matrix1.ndim}')
print(f'addition.shape is:  {matrix1.shape}')
print(f'addition.size is:   {matrix1.size}')
print(f'addition.dtypoe is: {matrix1.dtype}')

addition.ndim is:   2
addition.shape is:  (3, 2)
addition.size is:   6
addition.dtypoe is: int64


We also covered other methods to create matrices: `zeros`, `ones`, `empty` or `random.random`, each of which receive a tuple with the dimensions:
 - `zeros` generates matrices filled with zeros.
 - `ones` generates matrices filled with ones.
 - `empty` generates matrices, uninitialised.
 - `random.random` generates matrices with random numbers (uniformly distributed within the range $(0,1)$).

In [5]:
print('zeros')
z = numpy.zeros((2,2))
print(z)

print('ones')
o = numpy.ones((2,2))
print(o)

print('empty')
e = numpy.empty((3,3))
print(e)

print('random')
r = numpy.random.random((3,3))
print(r)

zeros
[[0. 0.]
 [0. 0.]]
ones
[[1. 1.]
 [1. 1.]]
empty
[[1.23516411e-322 6.08382738e-315 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
random
[[0.50440343 0.58062364 0.33404928]
 [0.47180403 0.23381295 0.01878936]
 [0.25927494 0.96545469 0.91128471]]


To access single elements of a matrix we specify the indices for each dimension in square brackets, separated by commas. For instance, to access the element in the second row, first column of the matrix we generated earlier using `numpy.random.random()` we can use the following code:

In [6]:
print(r[1,0])

0.47180403298386164


In this lab, we are going to continue from where we left it in `Lab 00`, but with a small change. Instead of importing numpy as:

`import numpy`

we will do the import using a Python's feature that allows us to rename modules:

`import numpy as np`

This is how NumPy is usually imported, just for the sake of conciseness.

In [7]:
import numpy as np

### Slicing lists
Slicing (selecting contiguous subsets of matrices) is going to be a very important operation in the module. Before learning how to slice matrices (that we will use to store images), let's do the same with basic Python lists. Consider the following list:

In [8]:
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

print(f'Our list has {len(l)} elements: {l}')
print(f'The element in index 5 is {l[5]}.')

Our list has 10 elements: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
The element in index 5 is f.


We have used the square brackets to select one single element. We can also use multiple using a colon (`:`). We will specify the beginning and the first element **not** to be included. See the following example:

In [9]:
print(f'The elements in index 5 to 6 are {l[5:6]}.')
print(f'The elements in index 5 to 7 are {l[5:7]}.')

The elements in index 5 to 6 are ['f'].
The elements in index 5 to 7 are ['f', 'g'].


We can also specify just the beginning or the end:

In [10]:
print(f'The elements from index 5 to the end are {l[5:]}.')
print(f'The elements from the beginning to index 5 (not included) {l[:5]}.')

The elements from index 5 to the end are ['f', 'g', 'h', 'i', 'j'].
The elements from the beginning to index 5 (not included) ['a', 'b', 'c', 'd', 'e'].


We can also use negative numbers to specify indices from the end, going backwards:

In [11]:
print(f'The elements from index 5 to the one before end are {l[5:-1]}.')

The elements from index 5 to the one before end are ['f', 'g', 'h', 'i'].


The last slicing feature that we will need to know is a third optional field used to specify the step size (it can be negative):

In [12]:
print(f'The elements from index 0 to the end (included, see the "+1") with a step of two are: {l[0:len(l)+1:2]}.')
print(f'The reversed elements from index 0 to the end (included) with a step of two are: {l[len(l)+1:0:-2]}.')

The elements from index 0 to the end (included, see the "+1") with a step of two are: ['a', 'c', 'e', 'g', 'i'].
The reversed elements from index 0 to the end (included) with a step of two are: ['j', 'h', 'f', 'd', 'b'].


## Slicing matrices
Now that we know how to do slicing on lists we only need to learn that we will generally use as many slicing expressions as dimensions in our matrices (separated by commas). If we use less than that Python will assume that we are doing slicing only in the first dimensions.

See the following example:

In [13]:
A = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8],
    [5,6,7,8,9]])

print('Whole matrix')
print(A)

print('Skipping the first and last row and column:')
print(A[1:4, 1:4])

print('Skipping the first and last row:')
print(A[1:4])


Whole matrix
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]
Skipping the first and last row and column:
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Skipping the first and last row:
[[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


Accessing a single item in a multidimensional array is exactly like accessing an slice, specifying a single element per dimension. For instance, to access and print the item in the 2nd row, 3rd column of the previous matrix $A$ we just use $1$ and $2$ as the indices (remember indices start at 0):

In [14]:
value = A[1, 2]
print(f'We get {value}')

We get 4


### Transposition
To transpose matrices we use the function `np.transpose`. It returns a transposed matrix and takes two arguments:
- a: The array to transpose.
- axes: An array or tuple indicating which is the desired order. If not specified, it reverses the order.

In [15]:
A = np.array([[1,2,3,4], [1,2,3,4]])
print('A')
print(A)
print('')

B = np.transpose(A, [1,0])
print('transposed')
print(B)
print('')


A
[[1 2 3 4]
 [1 2 3 4]]

transposed
[[1 1]
 [2 2]
 [3 3]
 [4 4]]



### Element-wise matrix multiplication
In the next cell we demonstrate how element-wise multiplication works, with a scalar and with a matrix. In both cases, we use the `*` operator for element-wise multiplication.

In [16]:
C = np.ones(A.shape)
print(f'C\n{C}\n')

D = C * 2
print(f'D\n{D}\n')

E = A * D
print(f'E\n{E}\n')

C
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

D
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]]

E
[[2. 4. 6. 8.]
 [2. 4. 6. 8.]]



### Matrix multiplication
It might have come to you as a surprise that we can multiply two $2x4$ matrices using the $*$ operator. That is because in NumPy element-wise is the default. In fact, most of the operations we will perform with matrices in CS3330 will be element-wise. It is still convenient to know the difference and be able to use both. To perform **actual** matrix multiplication we need to use the $@$ operator:

In [18]:
print(A.shape, D.shape)

E = A @ D
print(f'E\n{E}\n')

(2, 4) (2, 4)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

As you see from the error (please **remember to read error messages with attention**), to multiply matrices in the conventional way (not element-wise), the number of columns of the first matrix ($k$ in the error message) has to match the number of rows in the second. If we transpose one of the matrices using `np.transpose`, we meet that condition (for the previous example, not in general!):

In [19]:
transposed_D = np.transpose(D)

print(A.shape, transposed_D.shape)

E = A @ transposed_D
print(f'E\n{E}\n')

(2, 4) (4, 2)
E
[[20. 20.]
 [20. 20.]]



### Saving and loading matrices


In [20]:
A = np.ones((2,2))
print(f'A\n{A}\n')

B = np.array([[1,2], [3,4]])
print(f'B\n{B}\n')

np.savez('output.npz', A=A, B=B, number=1)

A
[[1. 1.]
 [1. 1.]]

B
[[1 2]
 [3 4]]



In [21]:
data = np.load('output.npz')
for key in data:
    print(key)

A
B
number


In [22]:
loaded_A = data['A']
print(f'loaded_A\n{loaded_A}\n')

loaded_B = data['B']
print(f'loaded_B\n{loaded_B}\n')

loaded_n = data['number']
print(f'loaded_n\n{loaded_n}\n')

loaded_A
[[1. 1.]
 [1. 1.]]

loaded_B
[[1 2]
 [3 4]]

loaded_n
1



##  Vectorising loops

You should now be in a position to start writing Python code working with NumPy arrays in terms of vectors and matrices, rather than loops. We will look at a simple example of taking loop-based code and vectorising it, and then you will complete some tasks to consolidate the learning.

For all examples, we will assume that we have the following matrices 
in our namespace:

In [23]:
# The following sets the floating point precision WHEN PRINTING
np.set_printoptions(precision=3)

# np.random.rand works similar to np.ones. Instead of 1's,
# it generates numbers using a standard normal distribution
v = np.random.random((1,8))-0.5
print(f'v\n{v}')
M = np.random.random((8,8))-0.5
print(f'M\n{M}')
N = np.random.random((8,8))-0.5
print(f'N\n{N}')

v
[[-0.347 -0.244  0.188 -0.023  0.463 -0.339  0.126 -0.234]]
M
[[ 0.095  0.227 -0.06  -0.394  0.092  0.32  -0.02   0.281]
 [ 0.449 -0.02  -0.427 -0.153 -0.1   -0.008  0.413  0.459]
 [-0.409  0.227  0.288  0.156 -0.249  0.302  0.391 -0.338]
 [ 0.248  0.273 -0.007 -0.285 -0.439  0.429 -0.278  0.047]
 [ 0.237 -0.161  0.017 -0.361 -0.168  0.189 -0.324  0.261]
 [ 0.391 -0.489  0.459 -0.222 -0.268  0.268 -0.268  0.303]
 [-0.257  0.158  0.314 -0.223  0.178  0.216 -0.455  0.149]
 [ 0.127 -0.098  0.016  0.038 -0.01  -0.321  0.395  0.173]]
N
[[-0.256  0.434 -0.244  0.362 -0.291  0.019 -0.221  0.303]
 [-0.106 -0.028  0.413 -0.311 -0.1   -0.178  0.487  0.045]
 [-0.464 -0.097 -0.15   0.446  0.379  0.21  -0.192 -0.41 ]
 [ 0.253 -0.288 -0.301 -0.064 -0.076 -0.216  0.167  0.025]
 [-0.191  0.13  -0.483  0.396 -0.265 -0.107  0.057 -0.436]
 [-0.063 -0.121  0.414 -0.228  0.076  0.386  0.311  0.49 ]
 [-0.498 -0.48  -0.051  0.487 -0.153  0.013 -0.392  0.184]
 [ 0.472  0.423 -0.368 -0.172 -0.446  0.211  0.1

Here, $M$ and $N$ are $8$ by $8$ matrices and $v$ is a length $8$ row vector, containing random elements drawn uniformly at random from the range $(-0.5,0.5)$.

The following cell sets all negative elements of $v$ to 0:

In [24]:
# We make the code work on a copy of the v to avoid overwriting it
w = np.array(v)
for i in range(w.shape[1]):
    if w[0,i] < 0:
        w[0,i] = 0
print(w)

[[0.    0.    0.188 0.    0.463 0.    0.126 0.   ]]


To vectorise this code, we need to learn about a new way to access matrices: **boolean masking**. It is very intuitive. Read the following code and try to guess what it does:

In [25]:
bmask = v < 0
print(bmask)

[[ True  True False  True False  True False  True]]


What the code does is to compute a matrix of the same shape as $v$ where the items that meet the condition(s) are set to `True` and the rest are set to `False`.

Note that the inequality in the index matches the inequality in the for loop. **This is a common pattern**.

We can use that matrix to filter the elements to which an operation applies:

In [26]:
# We make the code work on a copy of the v to avoid overwriting it
w = np.array(v)
bmask = w < 0
w[bmask] = 0
print(w)

[[0.    0.    0.188 0.    0.463 0.    0.126 0.   ]]


We can also do it in a single line. The following code use _the same_ boolean mask, but does not store it in a variable:

In [27]:
# We make the code work on a copy of the v to avoid overwriting it
w = np.array(v)
w[w < 0] = 0
print(w)

[[0.    0.    0.188 0.    0.463 0.    0.126 0.   ]]


NumPy applies logical operators (e.g., `and`, `or`) matrix-wise. Therefore, to make more complex boolean masks, will use `np.logical_and()`, `np.logical_or()`, `np.logical_not()` or `np.logical_xor()`. See the following examples:

In [28]:
A = np.random.random((5,5))-0.5
print(f'A:\n{A}')
B = np.random.random((5,5))-0.5
print(f'B:\n{B}')

bmask1 = A>B
bmask2 = B>0
print(f'A>B:\n{bmask1}')
print(f'B>0:\n{bmask2}')

print(f'result:\n{np.logical_and(bmask1, bmask2)}')

A:
[[-0.046  0.112 -0.402  0.337 -0.342]
 [ 0.485  0.051  0.262  0.487  0.441]
 [ 0.256  0.366 -0.144  0.433  0.246]
 [-0.468  0.251  0.294  0.358 -0.473]
 [-0.365 -0.001  0.146  0.389  0.479]]
B:
[[-0.098 -0.07  -0.398  0.413  0.462]
 [-0.272  0.208 -0.262 -0.46  -0.241]
 [ 0.137 -0.033 -0.04   0.5    0.119]
 [ 0.396  0.095 -0.029 -0.202  0.491]
 [ 0.094  0.143  0.496  0.111 -0.408]]
A>B:
[[ True  True False False False]
 [ True False  True  True  True]
 [ True  True False False  True]
 [False  True  True  True False]
 [False False False  True  True]]
B>0:
[[False False False  True  True]
 [False  True False False False]
 [ True False False  True  True]
 [ True  True False False  True]
 [ True  True  True  True False]]
result:
[[False False False False False]
 [False False False False False]
 [ True False False False  True]
 [False  True False False False]
 [False False False  True False]]


The following cell does not use conditionals. It multiplies elements of $M$ by the _cosine_ of the corresponding elements (with the same index) in $N$ and assigns the result to a new matrix P.



In [29]:
# We create a matrix of the same size as M
P = np.ones(M.shape)
# Loop
for i in range(M.shape[0]): # for every row
    for j in range(M.shape[1]): # for every column
        P[i,j] = M[i,j] * np.cos(N[i,j])
print(P)

[[ 0.092  0.206 -0.058 -0.368  0.088  0.32  -0.02   0.268]
 [ 0.447 -0.02  -0.391 -0.145 -0.1   -0.008  0.365  0.458]
 [-0.366  0.225  0.285  0.14  -0.231  0.296  0.383 -0.31 ]
 [ 0.24   0.261 -0.007 -0.284 -0.437  0.419 -0.274  0.047]
 [ 0.233 -0.16   0.015 -0.333 -0.163  0.188 -0.323  0.237]
 [ 0.39  -0.485  0.42  -0.217 -0.267  0.248 -0.255  0.267]
 [-0.226  0.14   0.313 -0.197  0.176  0.216 -0.421  0.146]
 [ 0.113 -0.089  0.015  0.037 -0.009 -0.314  0.392  0.165]]


To vectorise this code we only need to use our knowledge of elementwise operations and use the `np.cos` function for the cosine (the sine is implemented in `np.sin`):

In [30]:
# We create a matrix of the same size as M
P = M * np.cos(N)
print(P)

[[ 0.092  0.206 -0.058 -0.368  0.088  0.32  -0.02   0.268]
 [ 0.447 -0.02  -0.391 -0.145 -0.1   -0.008  0.365  0.458]
 [-0.366  0.225  0.285  0.14  -0.231  0.296  0.383 -0.31 ]
 [ 0.24   0.261 -0.007 -0.284 -0.437  0.419 -0.274  0.047]
 [ 0.233 -0.16   0.015 -0.333 -0.163  0.188 -0.323  0.237]
 [ 0.39  -0.485  0.42  -0.217 -0.267  0.248 -0.255  0.267]
 [-0.226  0.14   0.313 -0.197  0.176  0.216 -0.421  0.146]
 [ 0.113 -0.089  0.015  0.037 -0.009 -0.314  0.392  0.165]]


## Task 1.1: Working with NumPy array slices
Starting with a row vector $\mathbf{v1}$: $$v1 =\begin{bmatrix}1 & -1 & 2 & -2 & 3 & -3\end{bmatrix}$$

1. Extract the 3rd, 4th, and 5th elements (columns) of the vector into another vector $\mathbf{v2}$.
2. Replace the 6th element in $\mathbf{v1}$ with the value -4.
3. Replace the first 3 elements in $\mathbf{v1}$ with the numbers $1$, $2$ and $3$.
4. Set all positive numbers in $\mathbf{v1}$ to $0$.
5. Double all negative values in $\mathbf{v1}$.

In [36]:
# WRITE YOUR CODE BELOW (DO NOT DELETE THIS LINE)
# WRITE YOUR CODE ABOVE (DO NOT DELETE THIS LINE)

v1 = np.array([1, -1, 2, -2, 3, -3])
print(f'v1\n{v1}\n')
v2 = v1[2:5]
print(f'v2\n{v2}\n')

v1[5] = -4
print(f'v1:\n{v1}\n')

v1[:3] = [1, 2, 3]
print(f'v1:\n{v1}\n')

v1[v1>0] = 0
print(f'v1:\n{v1}\n')

v1[v1<0] = v1[v1<0] * 2
print(f'v1:\n{v1}\n')


v1
[ 1 -1  2 -2  3 -3]

v2
[ 2 -2  3]

v1:
[ 1 -1  2 -2  3 -4]

v1:
[ 1  2  3 -2  3 -4]

v1:
[ 0  0  0 -2  0 -4]

v1:
[ 0  0  0 -4  0 -8]



## Task 1.2 Vectorise the following loop-based code

### Task 1.2.1
The following loop iterates over the elements of $v$ and reverses the sign of negative elements.

In [ ]:
# We make the code work on a copy of the v to avoid overwriting it
w = np.array(v)
for i in range(w.shape[0]):
    for j in range(w.shape[1]):
        if w[i,j] < 0:
            w[i,j] = -w[i,j]
print(w)


In [37]:
# WRITE YOUR CODE BELOW (DO NOT DELETE THIS LINE)
v[v < 0] = -v[v < 0]
print(v)
# WRITE YOUR CODE ABOVE (DO NOT DELETE THIS LINE)

[[0.347 0.244 0.188 0.023 0.463 0.339 0.126 0.234]]


### Task 1.2.2
This loop does a slightly more complex calculation, using multiplication and sine.

In [ ]:
# We make the code work on a copy of the v to avoid overwriting it
w = np.array(v)
for i in range(w.shape[0]):
    for j in range(w.shape[1]):
        w[i,j] = 5. * w[i,j] * w[i,j] + np.sin(w[i,j])
print(w)

In [ ]:
# WRITE YOUR CODE BELOW (DO NOT DELETE THIS LINE)
v = 5. * v * v + np.sin(v)
print(v)
# WRITE YOUR CODE ABOVE (DO NOT DELETE THIS LINE)

## Task  1.2.3
The following loop requires operating with boolean masks. Make sure you use `np.logical_or` when writing your answer.

In [ ]:
# We make the code work on a copy of the v to avoid overwriting it
M2 = np.array(M)
for i in range(M2.shape[0]):
    for j in range(M2.shape[1]):
        if M2[i,j] < -0.25 or M2[i,j] > 0.25:
            M2[i,j] = M2[i,j]/2
print(M2)

In [ ]:
# WRITE YOUR CODE BELOW (DO NOT DELETE THIS LINE)
bmask1 = M < -0.25
bmask2 = M >  0.25
final_bmask = np.logical_or(bmask1, bmask2)
M[final_bmask] = M[final_bmask] / 2

# Compact solution
M[np.logical_or(M < -0.25, M > 0.25)] /= 2
# WRITE YOUR CODE ABOVE (DO NOT DELETE THIS LINE)

## Task 1.2.4
Last one. Make sure you respect the operator precedence. Operator precedence in Python is similar to that of C++ or Java: [you can check the documentation](https://docs.python.org/3/reference/expressions.html#operator-precedence).

In [ ]:
# We make the code work on a copy of the v to avoid overwriting it
M2 = np.array(M)
P = np.zeros(M2.shape)

for i in range(M2.shape[0]):
    for j in range(M2.shape[1]):
        P[i,j] = M[i,j]+N[i,j]+1
        P[i,j] = P[i,j]**2
print(P)

In [ ]:
# WRITE YOUR CODE BELOW (DO NOT DELETE THIS LINE)
M2 = np.array(M)
P = np.zeros(M2.shape)

P = (M+N+1)**2
print(P)
# WRITE YOUR CODE ABOVE (DO NOT DELETE THIS LINE)